/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

/**
 * A table the authorization package's migration created: no model reads it. The generator
 * names the class `pascalCase(singular(table))` with English rules — `papeis` gives `Papei`.
 */
export class PapeiSchema extends BaseModel {
  static $columns = ['id', 'nome', 'guarda', 'createdAt'] as const
  $columns = PapeiSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column()
  declare guarda: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}
