/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class UserSchema extends BaseModel {
  static $columns = ['id', 'email', 'fullName', 'createdAt'] as const
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class PostSchema extends BaseModel {
  static $columns = ['id', 'userId', 'title'] as const
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
  @column()
  declare title: string
}
