/**
 * This file is automatically generated
 * DO NOT EDIT manually
 */
import { BaseModel, column } from '@adonisjs/lucid/orm'

export class InvoiceSchema extends BaseModel {
  static $columns = ['id', 'total'] as const
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare total: number
}
