/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const listeners = {
  ReserveStock: () => import('#listeners/reserve_stock'),
  NotifyCarrier: () => import('#listeners/notify_carrier'),
}
