/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthorSchema extends BaseModel {
  static $columns = ['id', 'name', 'country', 'createdAt'] as const
  $columns = AuthorSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class BookSchema extends BaseModel {
  static $columns = ['id', 'authorId', 'title', 'isbn', 'publishedYear', 'createdAt'] as const
  $columns = BookSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare authorId: number
  @column()
  declare title: string
  @column()
  declare isbn: string | null
  @column()
  declare publishedYear: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}
