import { test } from '@japa/runner'
import path from 'node:path'

import { ConfigLoadError, loadConfig } from '../../src/cli/load_config.js'
import { printResult } from '../../src/cli/print.js'
import { runCount, runExplain, runInventory } from '../../src/cli/runners.js'
import { packageVersion, parseArgv, run } from '../../src/cli.js'
import { appFixturePath, fixturePath } from '../helpers.js'

const configFixture = (name: string) => fixturePath('configs', name)

/**
 * The defect this group exists to make impossible: `config/function_points.ts`
 * was generated by `configure`, typed by `defineConfig` and documented in the
 * README — and read by nobody. Every option but `--min-coverage` was silently
 * ignored by the command a user actually runs, while the tests proved the
 * options worked by calling `analyze()` directly.
 */
test.group('config loading', () => {
  test('loads the config file from the application root', async ({ assert }) => {
    const { config, file } = await loadConfig(configFixture('valid'))

    assert.deepEqual(config.boundary.infrastructure, ['Book'])
    assert.equal(config.maxDepth, 7)
    assert.match(file!, /config[/\\]function_points\.ts$/)
  })

  test('fills the defaults for what the file omits', async ({ assert }) => {
    const { config } = await loadConfig(configFixture('valid'))

    assert.equal(config.retStrategy, 'constant')
    assert.equal(config.messageDet, 0, 'the default follows AFP, not the IFPUG manual')
  })

  test('no config file is a legitimate state, not an error', async ({ assert }) => {
    const { config, file } = await loadConfig(configFixture('absent'))

    assert.isNull(file)
    assert.equal(config.maxDepth, 3)
  })

  /**
   * The most important test here. Falling back to the defaults with a warning —
   * which is what comparable tools do — would change the number silently, and
   * the number becomes an invoice.
   */
  test('a config that fails to load FAILS, it does not fall back', async ({ assert }) => {
    await assert.rejects(() => loadConfig(configFixture('broken')), ConfigLoadError)
  })

  test('the failure says the count was not produced, and what to do', async ({ assert }) => {
    try {
      await loadConfig(configFixture('broken'))
      assert.fail('should have thrown')
    } catch (error) {
      assert.match((error as Error).message, /was NOT produced/)
      assert.match((error as Error).message, /function_points\.ts/)
    }
  })

  test('a default export that is not an object also fails', async ({ assert }) => {
    await assert.rejects(() => loadConfig(configFixture('not_an_object')), ConfigLoadError)
  })
})

/**
 * The two front-ends must not be able to disagree about a number, so everything
 * that decides one lives in the runners and both call them.
 */
test.group('runners: the config reaches the count', () => {
  test('an option in the config file changes the count', async ({ assert }) => {
    const withoutConfig = await runCount({ root: appFixturePath('minimal_flat') })
    const withConfig = await runCount({ root: appFixturePath('configured') })

    assert.include(withoutConfig.output, 'Book')
    assert.notInclude(withConfig.output, '\nBook ')
    assert.notEqual(withConfig.output, withoutConfig.output)
  })

  test('every run says which configuration produced it', async ({ assert }) => {
    const configured = await runCount({ root: appFixturePath('configured') })
    const plain = await runCount({ root: appFixturePath('minimal_flat') })

    assert.isTrue(configured.notes!.some((note) => note.includes('function_points.ts')))
    assert.isTrue(plain.notes!.some((note) => note.includes('defaults')))
  })

  test('an explicit flag beats the config file', async ({ assert }) => {
    await assert.rejects(() => runCount({ root: appFixturePath('configured'), minCoverage: 1.01 }))
  })

  test('a function that matches nothing is an error, not empty output', async ({ assert }) => {
    const result = await runExplain({ root: appFixturePath('minimal_flat'), name: 'nope' })

    assert.isEmpty(result.output)
    assert.isNotEmpty(result.errors)
  })

  test('inventory reports coverage', async ({ assert }) => {
    const result = await runInventory({ root: appFixturePath('minimal_flat') })
    assert.match(result.output, /coverage:\s+\d+/)
  })
})

test.group('cli: argument parsing', () => {
  test('reads `--flag value` and `--flag=value` alike', ({ assert }) => {
    assert.equal(parseArgv(['count', '--root', 'a']).flags.get('root'), 'a')
    assert.equal(parseArgv(['count', '--root=a']).flags.get('root'), 'a')
  })

  test('a flag with no value is a boolean', ({ assert }) => {
    assert.isTrue(parseArgv(['count', '--json']).flags.get('json'))
  })

  test('keeps the command and its positional arguments apart', ({ assert }) => {
    const parsed = parseArgv(['explain', 'POST /books', '--json'])

    assert.equal(parsed.command, 'explain')
    assert.deepEqual(parsed.positional, ['POST /books'])
  })
})

test.group('cli: exit codes', () => {
  const silent = { log: () => {}, error: () => {} }

  /** captures what the CLI would print, so the suite stays quiet */
  const capture = () => {
    const lines: string[] = []
    return {
      lines,
      printer: { log: (m: string) => lines.push(m), error: (m: string) => lines.push(m) },
    }
  }

  test('a successful run exits 0', async ({ assert }) => {
    assert.equal(printResult(await runCount({ root: appFixturePath('minimal_flat') }), silent), 0)
  })

  test('an error exits 1, so CI fails', async ({ assert }) => {
    const result = await runExplain({ root: appFixturePath('minimal_flat'), name: 'nope' })
    assert.equal(printResult(result, silent), 1)
  })

  /**
   * Pointing at the wrong directory is the likeliest mistake in CI, and its
   * symptom would be a confident zero. Refusing beats counting nothing.
   */
  test('a root with no package.json is refused', async ({ assert }) => {
    const { lines, printer } = capture()
    const code = await run(
      ['count', '--root', path.join(appFixturePath('minimal_flat'), 'app')],
      printer
    )

    assert.equal(code, 1)
    assert.isTrue(lines.some((line) => line.includes('not an application root')))
  })

  test('an unknown command exits 1 and shows the usage', async ({ assert }) => {
    const { lines, printer } = capture()

    assert.equal(await run(['nonsense'], printer), 1)
    assert.isTrue(lines.some((line) => line.includes('unknown command')))
  })

  test('no command at all exits 1', async ({ assert }) => {
    const { printer } = capture()
    assert.equal(await run([], printer), 1)
  })

  test('--help exits 0 when asked for explicitly', async ({ assert }) => {
    const { printer } = capture()
    assert.equal(await run(['count', '--help'], printer), 0)
  })

  /** a flag documented in the usage that does nothing is the defect we keep fixing */
  test('--version prints the package version', async ({ assert }) => {
    const { lines, printer } = capture()

    assert.equal(await run(['--version'], printer), 0)
    assert.match(lines[0], /^\d+\.\d+\.\d+$/)
    assert.equal(lines[0], packageVersion())
  })
})
