import { test } from '@japa/runner'
import path from 'node:path'
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'

import { analyze } from '../../src/pipeline.js'

import { ConfigLoadError, loadConfig } from '../../src/cli/load_config.js'
import { printResult } from '../../src/cli/print.js'
import { runCount, runDiff, runExplain, runInventory, runMetrics } from '../../src/cli/runners.js'
import { packageVersion, parseArgv, run } from '../../src/cli.js'
import type { CountResult } from '../../src/types.js'
import { appFixturePath, fixturePath } from '../helpers.js'

const configFixture = (name: string) => fixturePath('configs', name)

/** a count with one function, enough to exercise pricing without analysing a tree */
const SYNTHETIC = {
  ruleset: 'afp',
  rulesetVersion: '1.0.0',
  functions: [
    {
      id: 'tx:POST /books',
      name: 'POST /books',
      module: 'app',
      type: 'EI',
      det: 3,
      refs: 1,
      complexity: 'low',
      points: 10,
      scopeHash: 'h1',
      rationale: { rule: 'afp:6.5.3', detSources: [], refSources: [] },
    },
  ],
  totals: { unadjusted: 10, byType: {}, byModule: {} },
  confidence: { unresolvedCalls: 0, entryPointsWithoutHandler: 0, warnings: [] },
} as unknown as CountResult

/**
 * The defect this group exists to make impossible: `config/function_points.ts`
 * was generated by `configure`, typed by `defineConfig` and documented in the
 * README — and read by nobody. Every option but `--min-coverage` was silently
 * ignored by the command a user actually runs, while the tests proved the
 * options worked by calling `analyze()` directly.
 */
test.group('config loading', () => {
  test('loads the config file from the application root', async ({ assert }) => {
    const { config, file } = await loadConfig(configFixture('valid'))

    assert.deepEqual(config.boundary.infrastructure, ['Book'])
    assert.equal(config.maxDepth, 7)
    assert.match(file!, /config[/\\]function_points\.ts$/)
  })

  test('fills the defaults for what the file omits', async ({ assert }) => {
    const { config } = await loadConfig(configFixture('valid'))

    assert.equal(config.retStrategy, 'constant')
    assert.equal(config.messageDet, 0, 'the default follows AFP, not the IFPUG manual')
  })

  test('no config file is a legitimate state, not an error', async ({ assert }) => {
    const { config, file } = await loadConfig(configFixture('absent'))

    assert.isNull(file)
    assert.equal(config.maxDepth, 3)
  })

  /**
   * The most important test here. Falling back to the defaults with a warning —
   * which is what comparable tools do — would change the number silently, and
   * the number becomes an invoice.
   */
  test('a config that fails to load FAILS, it does not fall back', async ({ assert }) => {
    await assert.rejects(() => loadConfig(configFixture('broken')), ConfigLoadError)
  })

  test('the failure says the count was not produced, and what to do', async ({ assert }) => {
    try {
      await loadConfig(configFixture('broken'))
      assert.fail('should have thrown')
    } catch (error) {
      assert.match((error as Error).message, /was NOT produced/)
      assert.match((error as Error).message, /function_points\.ts/)
    }
  })

  test('a default export that is not an object also fails', async ({ assert }) => {
    await assert.rejects(() => loadConfig(configFixture('not_an_object')), ConfigLoadError)
  })
})

/**
 * The two front-ends must not be able to disagree about a number, so everything
 * that decides one lives in the runners and both call them.
 */
test.group('runners: an empty inventory is never a number', () => {
  /**
   * Defence in depth behind the CLI guard: the ace front-end has no `--root` to
   * get wrong, but nothing else stops a runner returning `0 FP` for a directory
   * where it simply found nothing.
   */
  test('finding nothing is an error, not a count of zero', async ({ assert }) => {
    const result = await runCount({ root: fixturePath('monorepo') })

    assert.isEmpty(result.output)
    assert.isNotEmpty(result.errors)
    assert.isTrue(result.errors!.some((line) => line.includes('not a count of zero')))
  })

  test('the same holds for the inventory', async ({ assert }) => {
    const result = await runInventory({ root: fixturePath('monorepo') })
    assert.isNotEmpty(result.errors)
  })
})

test.group('runners: the config reaches the count', () => {
  test('an option in the config file changes the count', async ({ assert }) => {
    const withoutConfig = await runCount({ root: appFixturePath('minimal_flat') })
    const withConfig = await runCount({ root: appFixturePath('configured') })

    assert.include(withoutConfig.output, 'Book')
    assert.notInclude(withConfig.output, '\nBook ')
    assert.notEqual(withConfig.output, withoutConfig.output)
  })

  test('every run says which configuration produced it', async ({ assert }) => {
    const configured = await runCount({ root: appFixturePath('configured') })
    const plain = await runCount({ root: appFixturePath('minimal_flat') })

    assert.isTrue(configured.notes!.some((note) => note.includes('function_points.ts')))
    assert.isTrue(plain.notes!.some((note) => note.includes('defaults')))
  })

  test('an explicit flag beats the config file', async ({ assert }) => {
    await assert.rejects(() => runCount({ root: appFixturePath('configured'), minCoverage: 1.01 }))
  })

  test('a function that matches nothing is an error, not empty output', async ({ assert }) => {
    const result = await runExplain({ root: appFixturePath('minimal_flat'), name: 'nope' })

    assert.isEmpty(result.output)
    assert.isNotEmpty(result.errors)
  })

  test('inventory reports coverage', async ({ assert }) => {
    const result = await runInventory({ root: appFixturePath('minimal_flat') })
    assert.match(result.output, /coverage:\s+\d+/)
  })
})

/**
 * The shape CI has: a pipeline counts the base revision and the head revision,
 * and by the time they are compared neither is "the current working tree".
 */
test.group('runners: diff between two saved counts', () => {
  test('compares two files without analysing anything', async ({ assert }) => {
    const dir = await mkdtemp(path.join(tmpdir(), 'fp-diff-'))
    const base = path.join(dir, 'base.json')
    const head = path.join(dir, 'head.json')

    const { count } = await analyze(appFixturePath('minimal_flat'))
    await writeFile(base, JSON.stringify(count))
    await writeFile(head, JSON.stringify({ ...count, functions: count.functions.slice(1) }))

    const result = await runDiff({
      root: appFixturePath('minimal_flat'),
      previous: base,
      current: head,
    })

    assert.isEmpty(result.errors ?? [])
    assert.include(result.output, 'removed')
    assert.isTrue(
      result.notes!.some((note) => note.includes('minimal-flat')),
      'each side has to be named, or the comparison is unauditable'
    )
  })

  test('refuses two counts of different applications', async ({ assert }) => {
    const dir = await mkdtemp(path.join(tmpdir(), 'fp-diff-'))
    const base = path.join(dir, 'base.json')
    const head = path.join(dir, 'head.json')

    const flat = await analyze(appFixturePath('minimal_flat'))
    const hooks = await analyze(appFixturePath('model_hooks'))
    await writeFile(base, JSON.stringify(flat.count))
    await writeFile(head, JSON.stringify(hooks.count))

    const result = await runDiff({
      root: appFixturePath('minimal_flat'),
      previous: base,
      current: head,
    })

    assert.isNotEmpty(result.errors)
    assert.isTrue(result.errors!.some((line) => /different applications/.test(line)))
  })
})

test.group('cli: argument parsing', () => {
  test('reads `--flag value` and `--flag=value` alike', ({ assert }) => {
    assert.equal(parseArgv(['count', '--root', 'a']).flags.get('root'), 'a')
    assert.equal(parseArgv(['count', '--root=a']).flags.get('root'), 'a')
  })

  test('a flag with no value is a boolean', ({ assert }) => {
    assert.isTrue(parseArgv(['count', '--json']).flags.get('json'))
  })

  test('keeps the command and its positional arguments apart', ({ assert }) => {
    const parsed = parseArgv(['explain', 'POST /books', '--json'])

    assert.equal(parsed.command, 'explain')
    assert.deepEqual(parsed.positional, ['POST /books'])
  })
})

test.group('cli: exit codes', () => {
  const silent = { log: () => {}, error: () => {}, note: () => {} }

  /** captures what the CLI would print, so the suite stays quiet */
  const capture = () => {
    const out: string[] = []
    const notes: string[] = []
    return {
      lines: out,
      out,
      notes,
      printer: {
        log: (m: string) => void out.push(m),
        error: (m: string) => void out.push(m),
        note: (m: string) => void notes.push(m),
      },
    }
  }

  test('a successful run exits 0', async ({ assert }) => {
    assert.equal(printResult(await runCount({ root: appFixturePath('minimal_flat') }), silent), 0)
  })

  test('an error exits 1, so CI fails', async ({ assert }) => {
    const result = await runExplain({ root: appFixturePath('minimal_flat'), name: 'nope' })
    assert.equal(printResult(result, silent), 1)
  })

  /**
   * Pointing at the wrong directory is the likeliest mistake in CI, and its
   * symptom would be a confident zero. Refusing beats counting nothing.
   */
  test('a root that is not an AdonisJS application is refused', async ({ assert }) => {
    const { lines, printer } = capture()
    const code = await run(
      ['count', '--root', path.join(appFixturePath('minimal_flat'), 'app')],
      printer
    )

    assert.equal(code, 1)
    assert.isTrue(lines.some((line) => line.includes('not an AdonisJS application root')))
  })

  /**
   * The real case that found this: pointed at a monorepo root — which has a
   * package.json, so the old guard passed — the count came back 0 FP at 100%
   * coverage and exit 0. CI would have gone green on nothing.
   */
  test('a monorepo root is refused, not counted as zero', async ({ assert }) => {
    const { lines, printer } = capture()
    const monorepo = fixturePath('monorepo')

    const code = await run(['count', '--root', monorepo], printer)

    assert.equal(code, 1)
    assert.isTrue(lines.some((line) => /apps\/<name>|not an AdonisJS/.test(line)))
  })

  test('an unknown command exits 1 and shows the usage', async ({ assert }) => {
    const { lines, printer } = capture()

    assert.equal(await run(['nonsense'], printer), 1)
    assert.isTrue(lines.some((line) => line.includes('unknown command')))
  })

  test('no command at all exits 1', async ({ assert }) => {
    const { printer } = capture()
    assert.equal(await run([], printer), 1)
  })

  test('--help exits 0 when asked for explicitly', async ({ assert }) => {
    const { printer } = capture()
    assert.equal(await run(['count', '--help'], printer), 0)
  })

  /**
   * `--json` exists to be piped. A note on stdout makes the output unparseable,
   * which is a failure that only shows up in the CI job it was built for.
   */
  test('--json writes parseable JSON, with notes kept off stdout', async ({ assert }) => {
    const { out, notes, printer } = capture()

    assert.equal(
      await run(['count', '--root', appFixturePath('minimal_flat'), '--json'], printer),
      0
    )
    assert.doesNotThrow(() => JSON.parse(out.join('\n')))
    assert.isTrue(notes.some((note) => note.includes('config')))
  })

  /**
   * `measureStructure` and `measureConformance` were implemented, typed and
   * covered by tests, and reachable from no front-end. That is the recurring
   * defect of this package, and a metric nobody can run is not a metric.
   */
  test('metrics is a command, not just a function', async ({ assert }) => {
    const { out, printer } = capture()

    assert.equal(await run(['metrics', '--root', appFixturePath('minimal_flat')], printer), 0)
    assert.isTrue(out.some((line) => line.includes('FP per data store')))
    assert.isTrue(out.some((line) => line.includes('inputs with a validator')))
  })

  test('metrics --json is parseable, and carries the source', async ({ assert }) => {
    const { out, printer } = capture()

    assert.equal(
      await run(['metrics', '--root', appFixturePath('minimal_flat'), '--json'], printer),
      0
    )

    const parsed = JSON.parse(out.join('\n'))
    assert.exists(parsed.structure)
    assert.exists(parsed.conformance)
    assert.exists(parsed.source, 'a metric without its revision cannot be compared to another')
  })

  test('metrics refuses a root that is not the application', async ({ assert }) => {
    const result = await runMetrics({ root: fixturePath('monorepo') })

    assert.equal(printResult(result, silent), 1)
  })

  test('metrics reports the module graph it found', async ({ assert }) => {
    const { out, printer } = capture()

    await run(['metrics', '--root', appFixturePath('coupled_modules')], printer)

    /** the column header, and the two modules of the fixture under it */
    const lines = out.join('\n').split('\n')
    const header = lines.findIndex((line) => line.startsWith('module'))

    assert.isAbove(header, -1)
    assert.deepEqual(
      lines.slice(header + 1, header + 3).map((line) => line.split(' ')[0]),
      ['catalogo', 'faturamento']
    )
    assert.isTrue(
      lines[header + 2].includes('catalogo'),
      'faturamento depends on catalogo, and the report has to say on what'
    )
  })

  /** a flag documented in the usage that does nothing is the defect we keep fixing */
  test('--version prints the package version', async ({ assert }) => {
    const { lines, printer } = capture()

    assert.equal(await run(['--version'], printer), 0)
    assert.match(lines[0], /^\d+\.\d+\.\d+$/)
    assert.equal(lines[0], packageVersion())
  })
})

/**
 * `fp:diff` is what makes billing-by-change possible, so its pricing policy must
 * be reachable from the file the contract lives in. It was reachable from
 * nowhere: `factors` was a typed extension point only a test could use.
 */
test.group('cli: how change is priced', () => {
  const silentPrinter = { log: () => {}, error: () => {}, note: () => {} }

  test('the config file sets the change factors', async ({ assert }) => {
    const root = await mkdtemp(path.join(tmpdir(), 'fp-diff-'))
    const counts = path.join(root, 'counts')

    await writeFile(path.join(root, 'adonisrc.ts'), 'export default {}\n')
    await mkdir(path.join(root, 'config'), { recursive: true })
    await writeFile(
      path.join(root, 'config', 'function_points.ts'),
      `export default { diff: { reasonFactors: { implementation: 0.25 } } }\n`
    )

    const previous = { ...SYNTHETIC, functions: [SYNTHETIC.functions[0]] }
    const current = {
      ...SYNTHETIC,
      functions: [{ ...SYNTHETIC.functions[0], scopeHash: 'changed' }],
    }

    await writeFile(`${counts}-a.json`, JSON.stringify(previous))
    await writeFile(`${counts}-b.json`, JSON.stringify(current))

    const priced = await runDiff({
      root,
      previous: `${counts}-a.json`,
      current: `${counts}-b.json`,
    })
    const flat = await runDiff({
      root: appFixturePath('minimal_flat'),
      previous: `${counts}-a.json`,
      current: `${counts}-b.json`,
    })

    assert.equal(printResult(priced, silentPrinter), 0)
    assert.include(priced.output, 'Billable FP: 2.5')
    assert.include(flat.output, 'Billable FP: 10', 'without the config the default stands')
  })

  /**
   * On a real pair of releases the per-function list is over a hundred lines, and
   * the caveat about how most of the total was priced sat below all of them. A
   * warning that has to be scrolled to is not a warning.
   */
  test('a warning comes before the per-function list', async ({ assert }) => {
    const root = await mkdtemp(path.join(tmpdir(), 'fp-diff-order-'))
    const previous = path.join(root, 'a.json')
    const current = path.join(root, 'b.json')

    await writeFile(previous, JSON.stringify(SYNTHETIC))
    await writeFile(
      current,
      JSON.stringify({
        ...SYNTHETIC,
        functions: [{ ...SYNTHETIC.functions[0], scopeHash: 'changed' }],
      })
    )

    const { output } = await runDiff({
      root: appFixturePath('minimal_flat'),
      previous,
      current,
    })

    const lines = output.split('\n')
    const warning = lines.findIndex((line) => line.startsWith('Warning:'))
    /** the per-function list, anchored on the function name — not the summary row */
    const list = lines.findIndex((line) => line.includes('POST /books'))

    assert.isAbove(warning, -1)
    assert.isAbove(list, warning, 'the caveat is read before the hundred lines, not after')
  })
})
