/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class PedidoSchema extends BaseModel {
  static $columns = ['id', 'descricao', 'status', 'createdAt'] as const
  $columns = PedidoSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare descricao: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

/** a table a package's migration created: the application has no model for it, only this structure */
export class RegistroSchema extends BaseModel {
  static $columns = ['id', 'pedidoId', 'acao', 'autor', 'detalhe', 'createdAt', 'updatedAt'] as const
  $columns = RegistroSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pedidoId: number
  @column()
  declare acao: string
  @column()
  declare autor: string
  @column()
  declare detalhe: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
